plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.rfidasciidecoder'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.rfidasciidecoder"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // 這裡會自動引入 libs 資料夾內的所有 jar 檔（包含 UHF67_v3.6.jar）
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
